# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Buckets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buckets

  target 'BucketsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BucketsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'JSSAlertView'
pod ‘SCLAlertView’

end
